//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSW.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мебельный  магазин.
        /// </summary>
        public static string Index_gallery1 {
            get {
                return ResourceManager.GetString("Index_gallery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервация  для  мойки.
        /// </summary>
        public static string Index_gallery2 {
            get {
                return ResourceManager.GetString("Index_gallery2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация  праздников.
        /// </summary>
        public static string Index_gallery3 {
            get {
                return ResourceManager.GetString("Index_gallery3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ  панель  мойки.
        /// </summary>
        public static string Index_gallery4 {
            get {
                return ResourceManager.GetString("Index_gallery4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string Layout_AboutUs {
            get {
                return ResourceManager.GetString("Layout_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы.
        /// </summary>
        public static string Layout_AboutUs_Feedbacks {
            get {
                return ResourceManager.GetString("Layout_AboutUs_Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказать сайт.
        /// </summary>
        public static string Layout_AboutUs_News {
            get {
                return ResourceManager.GetString("Layout_AboutUs_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вопрос.
        /// </summary>
        public static string Layout_AskQuestion {
            get {
                return ResourceManager.GetString("Layout_AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фирма.
        /// </summary>
        public static string Layout_Company {
            get {
                return ResourceManager.GetString("Layout_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии.
        /// </summary>
        public static string Layout_Company_Vacancies {
            get {
                return ResourceManager.GetString("Layout_Company_Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Layout_Contacts {
            get {
                return ResourceManager.GetString("Layout_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агентство системных интернет-решений FutureSoftWare (FSW) | Создание и продвижение сайтов..
        /// </summary>
        public static string Layout_Copyright {
            get {
                return ResourceManager.GetString("Layout_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нашей.
        /// </summary>
        public static string Layout_LiButton_Blog {
            get {
                return ResourceManager.GetString("Layout_LiButton_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компании.
        /// </summary>
        public static string Layout_LiButton_Blog_more {
            get {
                return ResourceManager.GetString("Layout_LiButton_Blog_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши.
        /// </summary>
        public static string Layout_LiButton_Contact {
            get {
                return ResourceManager.GetString("Layout_LiButton_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Layout_LiButton_Contact_more {
            get {
                return ResourceManager.GetString("Layout_LiButton_Contact_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея.
        /// </summary>
        public static string Layout_LiButton_Portfolio {
            get {
                return ResourceManager.GetString("Layout_LiButton_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наших сайтов.
        /// </summary>
        public static string Layout_LiButton_Portfolio_more {
            get {
                return ResourceManager.GetString("Layout_LiButton_Portfolio_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить.
        /// </summary>
        public static string Layout_LiButton_Qoute {
            get {
                return ResourceManager.GetString("Layout_LiButton_Qoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзыв.
        /// </summary>
        public static string Layout_LiButton_Qoute_more {
            get {
                return ResourceManager.GetString("Layout_LiButton_Qoute_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказать.
        /// </summary>
        public static string Layout_LiButton_Services {
            get {
                return ResourceManager.GetString("Layout_LiButton_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веб-сайт.
        /// </summary>
        public static string Layout_LiButton_Services_more {
            get {
                return ResourceManager.GetString("Layout_LiButton_Services_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайн.
        /// </summary>
        public static string Layout_LiButton_Team {
            get {
                return ResourceManager.GetString("Layout_LiButton_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги.
        /// </summary>
        public static string Layout_LiButton_Team_more {
            get {
                return ResourceManager.GetString("Layout_LiButton_Team_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мессенджеры.
        /// </summary>
        public static string Layout_Messengers {
            get {
                return ResourceManager.GetString("Layout_Messengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звоните, пишите, пообщаемся, договоримся!.
        /// </summary>
        public static string Layout_Messengers_Call {
            get {
                return ResourceManager.GetString("Layout_Messengers_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги.
        /// </summary>
        public static string Layout_Services {
            get {
                return ResourceManager.GetString("Layout_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные услуг.
        /// </summary>
        public static string Layout_Services_AddOffers {
            get {
                return ResourceManager.GetString("Layout_Services_AddOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брифы.
        /// </summary>
        public static string Layout_Services_Briefs {
            get {
                return ResourceManager.GetString("Layout_Services_Briefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-дизайн сайтов.
        /// </summary>
        public static string Layout_Services_Design {
            get {
                return ResourceManager.GetString("Layout_Services_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработка сайтов.
        /// </summary>
        public static string Layout_Services_Develop {
            get {
                return ResourceManager.GetString("Layout_Services_Develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продвижение сайтов.
        /// </summary>
        public static string Layout_Services_Promotion {
            get {
                return ResourceManager.GetString("Layout_Services_Promotion", resourceCulture);
            }
        }
    }
}
